### ISSUE TITLE
hrsHR does not work

### ISSUE THREAD

**Issue by nonsub** [bmlt-enabled/bread#128]
Is displayed in PDF just as hrsHR

Old version Odathp works.

Thanks

**Comment by otrok7** [comment]
Hi, I think the only breaking change in v2 was that the "shortcodes" need to be set off (delimited) by non-alphanumerics.  This is much more stable, because it means we don't have to worry about shortcodes being substrings of other shortcodes.  But it also means that hrsHR is interpreted as a shortcode, not as a shortcode (hrs) followed by a string (HR).

The quick solution is to just set off the shortcode by brackets... these disappear when the page is generated.  That is [hrs]HR will produce the desired output.

Does that work for you, or do you need full backwards compatibility?

**Comment by pjaudiomv** [comment]
this seems to happen a bunch, I think the problem is in the templates. the templates need to be updated as this will happen if you use one

**Comment by otrok7** [comment]
templates are already updated.  the problem is during upgrades.  lets see if the user is satisfied with making the change...

**Comment by pjaudiomv** [comment]
is that the beta or next release there updated, its still broken in latest release on wordpress.org

**Comment by pjaudiomv** [comment]
Tri Fold - Letter Size

**Comment by pjaudiomv** [comment]
just saw the commit, it was right after last release. cool so itll be in next one.

**Comment by nonsub** [comment]
Thanks otrok! Funny I had tried this but with [hrsHR] by mistake I think! [hrs].. is fine thanks!
