### ISSUE TITLE
Save setting on BMLT server just hangs 

### ISSUE THREAD

**Issue by jefwheels** [bmlt-enabled/bread#170]
If I make updates to the meeting list and click save nothing happens. If I'm on the BMLT server page and click save it just spins. I know the server URL is correct and so is the service body
https://nerna.org/main_server
Greater Providence Area (6) New England Region (1)

**Comment by alanb2718** [comment]
Hi - unless I'm misunderstanding, it seems like this issue is about the root server meeting editor for New England Region, rather than bread.  If so and there is still a problem, try logging out, then clear all browser data and try again.  If this doesn't do it, please send an email to help@bmlt.app and someone can follow up.

**Comment by jefwheels** [comment]
Hey Alan 

 

I think it was the format config file. Once I started with a new file everything worked. 

 

Thanks for getting back to me
