### ISSUE TITLE
Bread cannot connect to server - no change

### ISSUE THREAD

**Issue by SuncoastIT** [bmlt-enabled/bread#176]
Nothing has changed with any plug in settings, credentials, or WP settings.  I can log in to the BMLT server.  But the plugin no longer can connect with the server, and therefore cannot generate the meeting list.  Tearing my hair out trying to figure out what might have changed.  Thoughts?

**Comment by californiasteve** [comment]
Are you using tomato for the server?

**Comment by SuncoastIT** [comment]
I dont have tomato enabled on the app, but I dont manage the server.

**Comment by californiasteve** [comment]
I connected from my test server using the https://bmlt.sezf.org/main_server/ server
https://californiasteve.rocks/?current-meeting-list=5

**Comment by otrok7** [comment]
Hi,

please check your SSL certificates.  I am getting a cURL 60 Error - Certificate has expired.  This would explain the sudden failure, with nothing changing... but not why browsers are not complaining.  So I will continue to investigate, but in the meantime, maybe this helps.

Ron

**Comment by otrok7** [comment]
OK, after a little more research, it seems like the likely cause of the problem is not the certificate on the server, but that the client (that is, whatever PHP Bread is running on) has an outdated PEM file.  If you have access to you PHP install, instructions to fix are here: https://noorsplugin.com/how-to-fix-curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/

If you are on a hosted server, you may need to contact your provider.

Let me know if this helps.

**Comment by SuncoastIT** [comment]
Thank you - once I provided this to my hosting company, they were able to
confirm that there is indeed a problem on their side.  No ETA on the
resolution, but its further than I've gotten.  Thank you!!!

**Comment by otrok7** [comment]
Have you downloaded the latest version of Bread?  I added something so that this sort of problem can be easilly diagnosed, and, in many cases, an optional workaround is provided.  If there is a certificate error, Bread should now give you the option of not checking the certificate.  As long as you are not sending a password, this should be OK.  I doubt anyone is doing MitM attacks on BMLT Servers.  Please give it a try.
