### ISSUE TITLE
Additional bread service body

### ISSUE THREAD

**Issue by sba408** [bmlt-enabled/bread#212]
I accidentally added another service body to my bread template. How do I remove it? I am not technical person. I have deleted the plugin and reinstalled it . However, it re-populates with both service bodies. I need this additional service body removed so I may print meeting list for my area.

**Comment by otrok7** [comment]
Hi.  I'm not sure if I understand the question.  Under "Settings->Meeting List" there is a tab for "BMLT Server".  On this page, there are 5 dropdown where you can select service bodies.  Once one is selected, you can always set it back to "Not Used".  Don't forget that all changes need to be saved, otherwise they don't affect the generated PDF.  Let me know if this information helps.  If I'm not understanding, then maybe post some screenshots to help me understand what the problem is.

**Comment by sba408** [comment]
Thank you so much for the help. My issue is solved.

Steven

________________________________
