### ISSUE TITLE
Full page meeting list

### ISSUE THREAD

**Issue by lucy12187** [bmlt-enabled/bread#39]
I can't figure out how to make a full page Meeting list look right.   Is there something I'm missing on this?

**Comment by pjaudiomv** [comment]
I don't believe this feature was ever finished, from reading note of the previous meeting list generator plugin.

**Comment by otrok7** [comment]
Added in 2.0

**Comment by lucy12187** [comment]
Great! This will be perfect for an area that doesn't have many meetings or just doesn't want a folded schedule. or even an area/region with LOTS of meetings that doesn't all fit on one piece of paper.

**Comment by otrok7** [comment]
For very small lists, there is also the flyer format...basically, 1 column of a tri-fold.  The system copies the front and back sides into the other 2 column, so that each page contains at the end 3 double sided meeting lists.  Hard to explain...look here: https://na-berlin.de/?current-meeting-list=4
    Am Freitag, 9. August 2019, 16:49:47 MESZ hat lucy12187 <notifications@github.com> Folgendes geschrieben:  
 
 
Great! This will be perfect for an area that doesn't have many meetings or just doesn't want a folded schedule. or even an area/region with LOTS of meetings that doesn't all fit on one piece of paper.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub, or mute the thread.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 40 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |
